import type { Metadata } from "next";
import { Geist, Geist_Mono, Hachi_Maru_Pop } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hachi = Hachi_Maru_Pop({
  variable: "--font-hachi-maru",
  subsets: ["latin"],
  weight: "400"
})
export const metadata: Metadata = {
  title: "Emotional LLMs 😃😭😡😨😮🤮",
  description: "Generated by an LLM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hachi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
